import { NextResponse } from 'next/server';
import { db } from '@/lib/firebase';
import { collection, addDoc } from 'firebase/firestore';

const mockProperties = [
  {
    title: 'Luxury Villa in Beverly Hills',
    description: 'Experience luxury living at its finest with panoramic city views, an infinity pool, and a dedicated home theater.',
    location: 'Los Angeles, CA',
    rentPerMonth: 15000,
    bedrooms: 5,
    bathrooms: 6,
    area: 4500,
    propertyType: 'villa',
    furnishing: 'furnished',
    amenities: ['Pool', 'Gym', 'Spa', 'Home Theater', 'Smart Home'],
    image: 'https://images.unsplash.com/photo-1627301077717-38f382218055?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Modern Downtown Loft',
    description: 'A sleek, industrial-style loft right in the heart of the city with floor-to-ceiling windows and exposed brick.',
    location: 'New York, NY',
    rentPerMonth: 4500,
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    propertyType: 'apartment',
    furnishing: 'semi',
    amenities: ['Gym', 'Doorman', 'Rooftop Lounge'],
    image: 'https://images.unsplash.com/photo-1541334239850-2f3b6d080f55?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Cozy Aspen Cabin',
    description: 'Disconnect from the world in this beautiful snowy cabin retreat featuring a natural stone fireplace.',
    location: 'Aspen, CO',
    rentPerMonth: 3200,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: 'house',
    furnishing: 'furnished',
    amenities: ['Fireplace', 'Hot Tub', 'Ski-in/Ski-out'],
    image: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Miami Beachfront Paradise',
    description: 'Step out of your back door and directly onto the white sand of Miami Beach. Features a private deck.',
    location: 'Miami, FL',
    rentPerMonth: 8500,
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    propertyType: 'villa',
    furnishing: 'furnished',
    amenities: ['Private Beach', 'Pool', 'Ocean View'],
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Charming Studio in Paris',
    description: 'A romantic studio in a historic arrondissement with a balcony overlooking classic Parisian streets.',
    location: 'Paris, France',
    rentPerMonth: 2100,
    bedrooms: 1,
    bathrooms: 1,
    area: 400,
    propertyType: 'room',
    furnishing: 'furnished',
    amenities: ['WiFi', 'Elevator', 'Balcony'],
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Spacious Family Home',
    description: 'A large suburban home perfect for a growing family, complete with a sprawling backyard and 2-car garage.',
    location: 'Austin, TX',
    rentPerMonth: 3500,
    bedrooms: 4,
    bathrooms: 2.5,
    area: 2800,
    propertyType: 'house',
    furnishing: 'unfurnished',
    amenities: ['Large Yard', 'Garage', 'Pet Friendly'],
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'London Riverside Apartment',
    description: 'Contemporary living by the Thames with impeccable amenities and sweeping views of the London skyline.',
    location: 'London, UK',
    rentPerMonth: 4200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: 'apartment',
    furnishing: 'furnished',
    amenities: ['Gym', 'Concierge', 'River View'],
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Rustic Tuscan Villa',
    description: 'A beautifully restored Italian farmhouse surrounded by vineyards and olive groves. Perfect for peaceful retreats.',
    location: 'Tuscany, Italy',
    rentPerMonth: 6000,
    bedrooms: 6,
    bathrooms: 4,
    area: 3500,
    propertyType: 'villa',
    furnishing: 'furnished',
    amenities: ['Pool', 'Wine Cellar', 'Garden'],
    image: 'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Minimalist Tokyo Apartment',
    description: 'Clean, simple, and zen minimal apartment in the heart of Shibuya. Ultra-modern appliances included.',
    location: 'Tokyo, Japan',
    rentPerMonth: 2800,
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    propertyType: 'apartment',
    furnishing: 'furnished',
    amenities: ['High-speed Internet', 'Subway Access'],
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Seattle Tech Hub Condo',
    description: 'Modern condo steps away from major tech campuses. Extremely fast internet and a spacious dedicated home office.',
    location: 'Seattle, WA',
    rentPerMonth: 3900,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    propertyType: 'apartment',
    furnishing: 'semi',
    amenities: ['Co-working Space', 'Gym', 'Parking'],
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'San Francisco Bay View House',
    description: 'Classic Victorian architecture with modern interiors and an unobstructed view of the Golden Gate Bridge.',
    location: 'San Francisco, CA',
    rentPerMonth: 7500,
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    propertyType: 'house',
    furnishing: 'unfurnished',
    amenities: ['Balcony', 'Fireplace', 'Garage'],
    image: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Dubai Marina Penthouse',
    description: 'Ultra-luxurious sky penthouse with private elevator access, infinity plunge pool, and panoramic marina views.',
    location: 'Dubai, UAE',
    rentPerMonth: 12000,
    bedrooms: 4,
    bathrooms: 5,
    area: 4000,
    propertyType: 'apartment',
    furnishing: 'furnished',
    amenities: ['Private Pool', 'Maid Room', 'Concierge'],
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Cozy Shared Room in Berlin',
    description: 'Affordable and lively room in a creative co-living space. Perfect for students or digital nomads.',
    location: 'Berlin, Germany',
    rentPerMonth: 900,
    bedrooms: 1,
    bathrooms: 1,
    area: 250,
    propertyType: 'room',
    furnishing: 'furnished',
    amenities: ['Shared Kitchen', 'WiFi', 'Laundry'],
    image: 'https://images.unsplash.com/photo-1522771731478-44fbcdfa4bc7?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Sunny Sydney Townhouse',
    description: 'Vibrant, sun-filled townhouse located just a short walk away from Bondi Beach.',
    location: 'Sydney, Australia',
    rentPerMonth: 4800,
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    propertyType: 'house',
    furnishing: 'semi',
    amenities: ['Patio', 'BBQ', 'Air Conditioning'],
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Historic Rome Apartment',
    description: 'Live like an ancient emperor in this stunningly renovated apartment next to the Colosseum.',
    location: 'Rome, Italy',
    rentPerMonth: 3400,
    bedrooms: 2,
    bathrooms: 1.5,
    area: 1000,
    propertyType: 'apartment',
    furnishing: 'furnished',
    amenities: ['AC', 'City View', 'Historic Architecture'],
    image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Secluded Bali Jungle Villa',
    description: 'Immerse yourself in nature in this incredible bamboo villa surrounded by lush Indonesian jungle.',
    location: 'Ubud, Bali',
    rentPerMonth: 2200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    propertyType: 'villa',
    furnishing: 'furnished',
    amenities: ['Private Pool', 'Yoga Deck', 'Garden'],
    image: 'https://images.unsplash.com/photo-1560963683-167bbac9d91f?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Chicago Skyline Highrise',
    description: 'Experience the Windy City from above in this luxury skyscraper apartment in the Loop.',
    location: 'Chicago, IL',
    rentPerMonth: 3700,
    bedrooms: 2,
    bathrooms: 2,
    area: 1150,
    propertyType: 'apartment',
    furnishing: 'unfurnished',
    amenities: ['Gym', 'Doorman', 'City View'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Vancouver Mountain Retreat',
    description: 'A gorgeous wood-paneled home nestled at the base of the mountains, built for outdoor enthusiasts.',
    location: 'Vancouver, Canada',
    rentPerMonth: 4100,
    bedrooms: 3,
    bathrooms: 2.5,
    area: 2100,
    propertyType: 'house',
    furnishing: 'semi',
    amenities: ['Fireplace', 'Deck', 'Hiking Trails'],
    image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Quiet Room in Toronto House',
    description: 'A comfortable, fully furnished private room in a quiet residential neighborhood close to transit.',
    location: 'Toronto, Canada',
    rentPerMonth: 1100,
    bedrooms: 1,
    bathrooms: 1,
    area: 200,
    propertyType: 'room',
    furnishing: 'furnished',
    amenities: ['WiFi', 'Shared Kitchen', 'Parking'],
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Cape Town Ocean Villa',
    description: 'Breathtaking ocean-view villa nestled on the cliffs overlooking the Atlantic. Includes a massive infinity pool.',
    location: 'Cape Town, South Africa',
    rentPerMonth: 5500,
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    propertyType: 'villa',
    furnishing: 'furnished',
    amenities: ['Pool', 'Security', 'Ocean View'],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Barcelona Gothic Quarter Flat',
    description: 'A stylish, bohemian flat located in the vibrant and historic heart of Barcelona.',
    location: 'Barcelona, Spain',
    rentPerMonth: 2600,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    propertyType: 'apartment',
    furnishing: 'furnished',
    amenities: ['Balcony', 'AC', 'Walkable'],
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  },
  {
    title: 'Seoul Gangnam Studio',
    description: 'Compact, ultra-efficient smart studio in the center of the bustling Gangnam district.',
    location: 'Seoul, South Korea',
    rentPerMonth: 1800,
    bedrooms: 1,
    bathrooms: 1,
    area: 350,
    propertyType: 'apartment',
    furnishing: 'furnished',
    amenities: ['Smart Home', 'Subway Access', 'Gym'],
    image: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
    hostId: 'admin_sys',
    createdAt: new Date().toISOString()
  }
];

export async function GET() {
  try {
    const colRef = collection(db, 'properties');
    
    const promises = mockProperties.map(p => addDoc(colRef, p));
    await Promise.all(promises);

    return NextResponse.json({ 
      success: true, 
      count: mockProperties.length,
      message: `Successfully seeded ${mockProperties.length} properties to Firebase.`
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
